[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[profile.dependencies]


chainlink = { git = "https://github.com/smartcontractkit/chainlink", rev = "v0.8", subdirs = ["evm-contracts/src/v0.8"] }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
