[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[profile.dependencies]

[profile.test]

rpcUrl = "https://sepolia.infura.io/v3/7214c971517a4856a1ea3c32a5ba8bd0"
forkBlockNumber = "latest" # Or specify a specific block number


chainlink = { git = "https://github.com/smartcontractkit/chainlink", rev = "v0.8", subdirs = ["evm-contracts/src/v0.8"] }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
